using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MNBEMART.Models
{
    public class PurchaseRequest
    {
        public int Id { get; set; }

        [Required, StringLength(50)]
        public string RequestNumber { get; set; } = string.Empty;

        [Required]
        public DateTime RequestDate { get; set; } = DateTime.Now;

        [Required]
        public int RequestedById { get; set; }
        public User? RequestedBy { get; set; }

        public PRStatus Status { get; set; } = PRStatus.Pending;

        [StringLength(500)]
        public string? Notes { get; set; }

        public int? ApprovedById { get; set; }
        public User? ApprovedBy { get; set; }

        public DateTime? ApprovedDate { get; set; }

        public bool IsAutoGenerated { get; set; } = false;

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime? UpdatedAt { get; set; }

        public List<PurchaseRequestDetail> Details { get; set; } = new();
    }

    public enum PRStatus
    {
        Pending,    // Chờ duyệt
        Approved,   // Đã duyệt
        Ordered,    // Đã đặt hàng
        Cancelled   // Đã hủy
    }
}






















































